server:
  port: 8080
spring:
  application:
    name: microservice-config-server
  cloud:
    config:
      server:
        git:
          #配置git仓库的地址
          uri: https://github.com/sugarlei/spring-cloud-config-repo
          #仓库路径
#          search-paths: demo
          username: 747459628@qq.com
          password: leiNING19920807/
        #自定义健康指示器的配置
        health:
          repositories:
            a-foo:
              label: config-label-v2.0
              name: microservice-foo
              profiles: dev
logging:
  level:
    org.springframework.cloud: debug
    org.springframework.boot: debug