server:
  port: 8763
spring:
  application:
    name: eureka-authenticating
  security:
    basic:
      enabled: true
    user:
      name: user #配置登录的账号是user
      password: 123456 #配置登录的密码是password123
eureka:
  instance:
    hostname: localhost
  client:
    register-with-eureka: false #是否将自己注册到 eureka server，默认为true,此处是 server, 所以不注册
    fetch-registry: false       #表示是否从eureka server 获取注册信息，默认为true,此处为单节点，不需要从其他eureka server同步 所以为false
    serviceUrl:                #与eureka server交互的地址，多个以逗号隔开，服务注册与发现依赖此地址
      defaultZone: http://user:123456@localhost:8763/eureka/