server:
  port: 8092
spring:
  application:          #指定注册到eureka server上的服务名称
    name: provider-user
  jpa:
    generate-ddl: false
    show-sql: true
    hibernate:
      ddl-auto: none
  datasource:                      #指定数据源
    platform: h2                    #指定数据类型
    schema: classpath:schema.sql    #指定h2数据库的建表脚本
    data: classpath:data.sql        #指定h2数据库的数据脚本
logging:
  level:
    root: INFO
    org.hibernate: INFO
    org.hibernate.type.descriptor.sql.BasicBinder: TRACE
    org.hibernate.type.descriptor.sql.BasicExtractor: TRACE
eureka:
  client:
    serviceUrl:
      defaultZone: http://user:123456@localhost:8763/eureka/
  #http://localhost:8761/eureka/,http://localhost:8762/eureka/
  instance:
    prefer-ip-address: true #表示将自己的IP注册到 eureka server 如果不设置 则默认为false 则表示讲服务所在的机器的hostname注册到 eureka server